services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: "64M"
          cpus: "0.25"
        limits:
          memory: "2048M"
          cpus: "0.5"

  api_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: "64M"
          cpus: "0.25"
        limits:
          memory: "2048M"
          cpus: "0.5"

  api_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:latest
    deploy:
      replicas: 2
      resources:
        reservations:
          memory: "64M"
          cpus: "0.25"
        limits:
          memory: "2048M"
          cpus: "0.5"

  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: "64M"
          cpus: "0.25"
        limits:
          memory: "2048M"
          cpus: "0.5"
